# Generated by Django 3.1.3 on 2020-11-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=255, null=True)),
                ('attorney', models.CharField(blank=True, max_length=255, null=True)),
                ('court_session', models.CharField(blank=True, max_length=255, null=True)),
                ('plea_request', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
