# Generated by Django 3.1.3 on 2020-11-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_number',
            new_name='offense',
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_session',
        ),
        migrations.AddField(
            model_name='case',
            name='complainant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='defendant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='file_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='no',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='attorney',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='plea_request',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
