# Generated by Django 3.1.3 on 2020-11-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20201109_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='response_by',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
