# Generated by Django 3.1.3 on 2020-11-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_case_response_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='continuance_request',
            field=models.DateField(blank=True, null=True),
        ),
    ]
