# Generated by Django 3.1.3 on 2020-11-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_case_continuance_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='continuance_request',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='response_by',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
