# Generated by Django 3.1.3 on 2020-11-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20201112_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='continuance_request',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
