# Generated by Django 3.1.3 on 2020-11-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20201112_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='continuance_request',
        ),
        migrations.RemoveField(
            model_name='case',
            name='defendant_name',
        ),
        migrations.AddField(
            model_name='case',
            name='court_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='defendant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='attorney',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='complainant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='file_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='no',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='offense',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='plea_request',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='response_by',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
