# Generated by Django 3.1.3 on 2020-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20201112_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_name', models.CharField(blank=True, max_length=50, null=True)),
                ('continuance', models.DateField(blank=True, null=True)),
                ('plea', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='attorney',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='complainant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='defendant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='file_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='no',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='offense',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='plea_request',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='response_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
