# Generated by Django 3.1.3 on 2020-11-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20201114_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='attendance.case'),
            preserve_default=False,
        ),
    ]
