# Generated by Django 3.1.3 on 2020-11-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20201114_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='plea',
        ),
    ]
