# Generated by Django 3.1.3 on 2020-11-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_case_plea'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='disposition',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
