# Generated by Django 3.1.3 on 2020-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_case_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='a',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='l',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='p',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
