# Generated by Django 3.1.3 on 2020-11-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20201117_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='plea_request',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
