# Generated by Django 3.1.3 on 2020-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20201117_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='disposition',
            field=models.TextField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='plea_request',
            field=models.TextField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='response_by',
            field=models.TextField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
