# Generated by Django 3.1.3 on 2020-11-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20201117_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='disposition',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
