# Generated by Django 3.1.3 on 2020-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_auto_20201117_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='continuance',
            field=models.CharField(blank=True, default='Unrequested', max_length=12, null=True),
        ),
    ]
