# Generated by Django 3.1.3 on 2020-11-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_auto_20201117_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cont_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
