# Generated by Django 3.1.3 on 2020-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_case_cont_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cont_approved',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
