# Generated by Django 3.1.3 on 2020-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_auto_20201117_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cont_consent',
            field=models.CharField(blank=True, default='Unresponded', max_length=5, null=True),
        ),
    ]
