# Generated by Django 3.1.3 on 2020-11-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_auto_20201117_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='disposition',
            field=models.TextField(blank=True, default='_ _ _', max_length=200, null=True),
        ),
    ]
