# Generated by Django 3.1.3 on 2020-11-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_auto_20201118_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cont_consent',
            field=models.CharField(blank=True, default='---', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='continuance',
            field=models.CharField(blank=True, default='---', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='defense_name',
            field=models.CharField(blank=True, default='---', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='disposition',
            field=models.TextField(blank=True, default='---', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='plea_request',
            field=models.TextField(blank=True, default='---', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='response_by',
            field=models.TextField(blank=True, default='---', max_length=200, null=True),
        ),
    ]
